// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "SOCKS5 127.0.0.1:4433; SOCKS 127.0.0.1:4433; DIRECT;";

function FindProxyForURL(url, host) {
    return proxy;
}
