version: '2' 
services:
  lightsocks:
    image: xxxooo
    restart: always
    volumes: 
      - ./:/root
    ports: 
      - "1024:1024" 
    environment:
      - LIGHT_MODULE
    command: $LIGHT_MODULE
